# Generated by Django 5.2 on 2025-05-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menuitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('guest_count', models.IntegerField()),
                ('reservation_time', models.DateField(auto_now=True)),
                ('comments', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TAform',
            fields=[
                ('TA_ID', models.AutoField(primary_key=True, serialize=False)),
                ('introduction', models.TextField()),
                ('goals', models.TextField()),
                ('materials', models.TextField()),
                ('instructions', models.TextField()),
                ('observation', models.TextField()),
                ('tips', models.TextField()),
                ('extensions', models.TextField()),
                ('resources', models.TextField()),
                ('comments', models.TextField()),
                ('status_tracking', models.CharField(max_length=100)),
                ('current_status', models.CharField(max_length=100)),
            ],
        ),
    ]
